FROM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /customer-service ./cmd/customer-service

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /customer-service /customer-service

EXPOSE 9090

CMD ["/customer-service"]
