FROM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /shipment-service ./cmd/shipment-service

FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /shipment-service /shipment-service

EXPOSE 8080

CMD ["/shipment-service"]
